apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: a3p3ct/nextjs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
          - name: NEXT_PUBLIC_API_URL
            valueFrom:
              configMapKeyRef:
                name: nextjs-config
                key: NEXT_PUBLIC_API_URL